### ISSUE TITLE
No release version

### ISSUE THREAD

**Issue by developerRojina** [sapkotamadhusudan/nepali-calendar#1]
I cannot see the latest version under the releases. Can you add the release version

**Comment by sapkotamadhusudan** [comment]
@developerRojina Hi, I've added the latest release, and in future I'll be adding full change log  of this library changes.
You can view all the releases of core and ui module in [Core Module](https://search.maven.org/artifact/io.github.sapkotamadhusudan/np-calendar-core) [UI Module](https://search.maven.org/artifact/io.github.sapkotamadhusudan/np-calendar-ui)

**Comment by developerRojina** [comment]
Hello @sapkotamadhusudan  Thank you for your reply. Thank you for you effort for making this library. Can you also provide me some documentation about how can I use this library.
The two things I need is:
AD to BS conversion
Nepali date picker 

Thank you

**Comment by sapkotamadhusudan** [comment]
@developerRojina 
- I've updated the core module README with [Instantiation](https://github.com/sapkotamadhusudan/nepali-calendar/blob/master/core/README.md#create-instance) & [Conversion](https://github.com/sapkotamadhusudan/nepali-calendar/blob/master/core/README.md#date-conversion) examples.
- There is no date picker available in this library, but you can take a look at examples for creating your own date picker [Example2](https://github.com/sapkotamadhusudan/nepali-calendar/blob/master/sample/src/main/java/com/maddy/calendar/sample/Example2Fragment.kt) & [Example4](https://github.com/sapkotamadhusudan/nepali-calendar/blob/master/sample/src/main/java/com/maddy/calendar/sample/Example4Fragment.kt)
